/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ListPackageImport } from './routes/list-package'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ListPackageRoute = ListPackageImport.update({
  id: '/list-package',
  path: '/list-package',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/list-package': {
      id: '/list-package'
      path: '/list-package'
      fullPath: '/list-package'
      preLoaderRoute: typeof ListPackageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/list-package': typeof ListPackageRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/list-package': typeof ListPackageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/list-package': typeof ListPackageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/list-package'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/list-package'
  id: '__root__' | '/' | '/list-package'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListPackageRoute: typeof ListPackageRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListPackageRoute: ListPackageRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/list-package"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/list-package": {
      "filePath": "list-package.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
